### ISSUE TITLE
4.0.4 incompatible

### ISSUE THREAD

**Issue by MarcEngrie** [milesburton/Arduino-Temperature-Control-Library#281]
Hi,

I am running Platformio on VS Code. In one of my ESP32 project I am using your library "DallasTemperature". The version I am using is 3.11.0 (on platform Espressif 32 version 6.11.0). 

In the meanwhile you updated the lib to version 4.0.4, But Platformio tells me that an update to 4.0.4 is incompatible.

Can you tell me why or what I need to do to make it compatible again and able to upgrade now (and later on)?

![Image](https://github.com/user-attachments/assets/0af8b091-bcb5-40c9-aa1e-d2b11d3d21d0)

**Comment by milesburton** [comment]
Hmm, that's curious. You can stick on the current version, 4.0.4 included some minor security fixes - no functional changes. Let me explore the incompatibility issues that have been flagged up.

**Comment by milesburton** [comment]
OK the reason is platformio is looking up via Github and I have yet to tag 4.0.4 so it's failing. I'll fix this shortly

**Comment by milesburton** [comment]
That should work now, can you verify?

**Comment by MarcEngrie** [comment]
just (Tue 02/09/2025 - 13:03 EST) tried and still the same. maybe I have to do something extra like ... ???

<img width="1117" height="433" alt="Image" src="https://github.com/user-attachments/assets/9d72cb94-4df0-4159-9a5b-05dbcc3d55be" />

**Comment by RobTillaart** [comment]
<img width="1339" height="586" alt="Image" src="https://github.com/user-attachments/assets/11930e6d-c21b-43e1-acd9-2d0d976823e8" />

Seems updated on PlatformIO.
Shows mixed 4.0.4 and 4.0.5 labels - some may take more time to update (?).

**Comment by milesburton** [comment]
As Rob mentioned, it may have not yet been propagated. I would suggest
using an older version. The last few versions are minor bug fixes and docs,
nothing ground breaking.
